create table tb_category (id bigint generated by default as identity, description TEXT, name varchar(255), primary key (id));
create table tb_event (category_id bigint, date_time timestamp(6), id bigint generated by default as identity, location_id bigint, description TEXT, name varchar(255), primary key (id));
create table tb_location (id bigint generated by default as identity, address varchar(255), city varchar(255), country varchar(255), name varchar(255), primary key (id));
alter table if exists tb_event add constraint FKmjjacuesrwbq0b1vhqrmetln5 foreign key (category_id) references tb_category;
alter table if exists tb_event add constraint FKqb5pdlcv5dyphpk88b51bhvnt foreign key (location_id) references tb_location;
